<?php
declare(strict_types=1);
return [
    "routes" => [
        ["name" => "page#index", "url" => "/", "verb" => "GET"],
        ["name" => "api#folders", "url" => "/api/v1/folders", "verb" => "GET"],
        ["name" => "api#photos", "url" => "/api/v1/photos", "verb" => "GET"],
        ["name" => "api#photo", "url" => "/api/v1/photos/{fileId}", "verb" => "GET"],
        ["name" => "api#preview", "url" => "/api/v1/preview/{fileId}", "verb" => "GET"],
        ["name" => "api#stats", "url" => "/api/v1/stats", "verb" => "GET"],
        ["name" => "api#clusters", "url" => "/api/v1/clusters", "verb" => "GET"],
        ["name" => "api#similarClusters", "url" => "/api/v1/similar-clusters", "verb" => "GET"],
        ["name" => "api#scanStatus", "url" => "/api/v1/scan-status", "verb" => "GET"],
        ["name" => "api#clusterDetail", "url" => "/api/v1/cluster-detail", "verb" => "GET"],
        ["name" => "vote#vote", "url" => "/api/v1/vote", "verb" => "POST"],
        ["name" => "vote#getMyVotes", "url" => "/api/v1/my-votes", "verb" => "GET"],
        ["name" => "vote#getVoteStats", "url" => "/api/v1/vote-stats/{fileId}", "verb" => "GET"],
        ["name" => "vote#batchSync", "url" => "/api/v1/vote/batch-sync", "verb" => "POST"],
        ["name" => "vote#bulkDelete", "url" => "/api/v1/vote/bulk-delete", "verb" => "POST"],
        ["name" => "vote#bulkKeep", "url" => "/api/v1/vote/bulk-keep", "verb" => "POST"],
        ["name" => "dashboardApi#unvoted", "url" => "/api/v1/dashboard/unvoted", "verb" => "GET"],
        ["name" => "dashboardApi#myVotes", "url" => "/api/v1/dashboard/my-votes", "verb" => "GET"],
        ["name" => "dashboardApi#statistics", "url" => "/api/v1/dashboard/statistics", "verb" => "GET"],
        ["name" => "dashboardApi#groupVotes", "url" => "/api/v1/dashboard/group-votes", "verb" => "GET"],
        ["name" => "dashboardApi#consensus", "url" => "/api/v1/dashboard/consensus", "verb" => "GET"],
        ["name" => "dashboardApi#folderUsers", "url" => "/api/v1/dashboard/folder-users", "verb" => "GET"],
        ["name" => "dashboardApi#folderInfo", "url" => "/api/v1/dashboard/folder-info", "verb" => "GET"],
        ["name" => "cleanup#execute", "url" => "/api/v1/cleanup/execute", "verb" => "POST"],
        ["name" => "cleanup#preview", "url" => "/api/v1/cleanup/preview", "verb" => "GET"],
        ["name" => "cleanup#quarantine", "url" => "/api/v1/cleanup/quarantine", "verb" => "GET"],
        ["name" => "cleanup#restore", "url" => "/api/v1/cleanup/restore", "verb" => "POST"],
        ["name" => "cleanup#emptyQuarantine", "url" => "/api/v1/cleanup/empty-quarantine", "verb" => "POST"],
        ["name" => "vote#deleteAll", "url" => "/api/v1/vote/delete-all", "verb" => "DELETE"],
    ],
];
